language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python3 database_utils.py config-example.yml True
services:
  - mysql


before_script:
- mysql -u root -e 'CREATE DATABASE bookmarks_db;'
- mysql -u root -e "CREATE USER 'generic_user'@'localhost' IDENTIFIED BY 'P@sSw0rd';"
- mysql -u root -e "GRANT ALL ON bookmarks_db.* TO 'generic_user'@'localhost';"
