version: 1
formatters:
  simple:
    format: '%(name)s - %(asctime)s - %(levelname)s - %(message)s'
  verbose:
    format: '%(name)s - %(asctime)s - %(filename)s:%(funcName)s - %(levelname)s - %(message)s'
  super_verbose:
    format: '%(name)s - %(asctime)s - %(module)s:%(filename)s:%(lineno)d(%(funcName)s) - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: verbose
    stream: ext://sys.stdout
loggers:
  mainLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]